# Generated by Django 4.2.4 on 2024-01-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
