# Generated by Django 4.2.4 on 2024-01-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
