# Generated by Django 4.2.4 on 2024-01-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0010_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='approve',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
