# Generated by Django 4.2.4 on 2024-01-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0012_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
